# Generated by Django 6.0.7 on 2026-07-31 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('video_introduction', models.FileField(blank=True, null=True, upload_to='profile_videos/')),
                ('about_me', models.TextField(blank=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('complexion', models.CharField(blank=True, max_length=100)),
                ('highest_education', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('religion', models.CharField(max_length=100)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('rashi', models.CharField(blank=True, max_length=100)),
                ('nakshatra', models.CharField(blank=True, max_length=100)),
                ('dosha', models.CharField(blank=True, max_length=100)),
                ('family_information', models.TextField(blank=True)),
                ('diet', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Eggetarian', 'Eggetarian')], max_length=20)),
                ('smoking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], max_length=20)),
                ('drinking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], max_length=20)),
                ('languages_known', models.CharField(help_text='Example: Telugu, English, Hindi', max_length=255)),
                ('hobbies_interests', models.TextField(blank=True)),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('disability_information', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['-id'],
            },
        ),
    ]
