# Generated by Django 6.0.7 on 2026-07-31 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_age', models.PositiveIntegerField()),
                ('maximum_age', models.PositiveIntegerField()),
                ('minimum_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('maximum_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('minimum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('lifestyle_preferences', models.TextField(blank=True)),
                ('horoscope_preferences', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_preferences',
                'ordering': ['-id'],
            },
        ),
    ]
