# Generated by Django 6.0.7 on 2026-07-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpreference',
            name='lifestyle_preferences',
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='diet',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Eggetarian', 'Eggetarian')], max_length=20),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='drinking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], max_length=20),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], max_length=20),
        ),
    ]
