# Generated by Django 6.0.7 on 2026-08-04 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('VOICE', 'Voice'), ('VIDEO', 'Video')], max_length=10)),
                ('status', models.CharField(choices=[('RINGING', 'Ringing'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ENDED', 'Ended')], default='RINGING', max_length=20)),
                ('sdp_offer', models.TextField(blank=True, null=True)),
                ('sdp_answer', models.TextField(blank=True, null=True)),
                ('caller_candidates', models.TextField(default='[]')),
                ('receiver_candidates', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_call_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
