# Generated by Django 6.0.7 on 2026-08-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_useronlinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by_p1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_p2',
            field=models.BooleanField(default=False),
        ),
    ]
